name: Release Notification

on:
  release:
    types: [ published ]

jobs:
  send-release-message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get the version
        id: version
        run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}

      - name: Send message to Telegram channel
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_RELEASE_CHANNEL_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdown
          message: |
            🆕 *Обновление социального рейтинга* 🆕

            ${{ github.event.release.body }}

            _Текущая версия: ${{ steps.version.outputs.version }}_
